### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by emtoonst** [moderation/garmin-connect-export#17]
After using python3 gcexport3.py and logging in I get the error 'TypeError: the JSON object must be str, not 'bytes''

I have solved this issue by detecting the encoding : 
Instead of LIST = json.loads(ACTIVITY_LIST) use:
LIST = json.loads(ACTIVITY_LIST.decode(chardet.detect(ACTIVITY_LIST)["encoding"]))

and instead of #JSON_SUMMARY = json.loads(ACTIVITY_SUMMARY) use:
JSON_SUMMARY = json.loads(ACTIVITY_SUMMARY.decode(chardet.detect(ACTIVITY_SUMMARY)["encoding"]))

you have to install and use the module chardet:
pip3 install chardet
add 'import chardet' to gcexport3.py

**Comment by moderation** [comment]
I've just merged https://github.com/moderation/garmin-connect-export/pull/20. I _think_ it may fix this - can you retest @emtoonst?

**Comment by emtoonst** [comment]
I have performed a retest, unfortunately the problems stills exists: 

`Traceback (most recent call last):
  File "gcexport3.py", line 375, in <module>
    LIST = json.loads(ACTIVITY_LIST)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'`

**Comment by emtoonst** [comment]
explicitly stating the ascii encoding in the decode function also solves the problem:

`LIST = json.loads(ACTIVITY_LIST.decode("ascii"))`
and 
`JSON_SUMMARY = json.loads(ACTIVITY_SUMMARY.decode("ascii"))`

**Comment by moderation** [comment]
Stale
